# Generated by Django 4.2.16 on 2024-10-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "remove_user_try_auth_count"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "users" DROP COLUMN "try_auth_count";'
                    )
                )
            ]
        )
    ]
