# Generated by Django 4.2.16 on 2024-10-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="try_auth_count",
            field=models.IntegerField(
                default=0, null=True, verbose_name="tentativas de autenticação"
            ),
        ),
    ]
