# Generated by Django 4.2.16 on 2024-10-31 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_try_auth_count"),
    ]

    operations = [
            migrations.SeparateDatabaseAndState(
                state_operations=[
                migrations.RemoveField(
                    model_name="user",
                    name="try_auth_count",
                ),
            ],
            database_operations=[],
        )
    ]
